apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharestats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharestats
  template:
    metadata:
      labels:
        app: sharestats
    spec:
      containers:
        - name: sharestats
          image: josephfajardo/portfolio-sharestats
          env:
            - name: JWT_SECRET
              value: "qwerty"
            - name: PORT
              value: "9000"
---
apiVersion: v1
kind: Service
metadata:
  name: sharestats-srv
spec:
  selector:
    app: sharestats
  ports:
    - name: sharestats-srv
      protocol: TCP
      port: 9000
      targetPort: 9000
